export const ListConstants={
    ADD_NEW_LIST_REQUEST:'ADD_NEW_LIST_REQUEST',
    ADD_NEW_LIST_SUCCESS:'ADD_NEW_LIST_SUCCESS',
    ADD_NEW_LIST_FAILURE:'ADD_NEW_LIST_FAILURE'
}

export const TodoConstants={
    ADD_NEW_TODO_REQUEST:'ADD_NEW_TODO_REQUEST',
    ADD_NEW_TODO_SUCCESS:'ADD_NEW_TODO_SUCCESS',
    ADD_NEW_TODO_FAILURE:'ADD_NEW_TODO_FAILURE'
}
