export const ListConstants={
    ADD_NEW_LIST_REQUEST:'ADD_NEW_LIST_REQUEST',
    ADD_NEW_LIST_SUCCESS:'ADD_NEW_LIST_SUCCESS',
    ADD_NEW_LIST_FAILURE:'ADD_NEW_LIST_FAILURE',

    DELETE_LIST_REQUEST:'DELETE_LIST_REQUEST',
    DELETE_LIST_SUCCESS:'DELETE_LIST_SUCCESS',
    DELETE_LIST_FAILURE:'DELETE_LIST_FAILURE',

    EDIT_LIST_REQUEST:'EDIT_LIST_REQUEST',
    EDIT_LIST_SUCCESS:'EDIT_LIST_SUCCESS',
    EDIT_LIST_FAILURE:'EDIT_LIST_FAILURE',

}

export const TodoConstants={
    ADD_NEW_TODO_REQUEST:'ADD_NEW_TODO_REQUEST',
    ADD_NEW_TODO_SUCCESS:'ADD_NEW_TODO_SUCCESS',
    ADD_NEW_TODO_FAILURE:'ADD_NEW_TODO_FAILURE',

    DELETE_TODO_REQUEST:'DELETE_TODO_REQUEST',
    DELETE_TODO_SUCCESS:'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAILURE:'DELETE_TODO_FAILURE',

    EDIT_TODO_REQUEST:'EDIT_TODO_REQUEST',
    EDIT_TODO_SUCCESS:'EDIT_TODO_SUCCESS',
    EDIT_TODO_FAILURE:'EDIT_TODO_FAILURE'
}

export const BoardsConstants={
    EDIT_BOARD_REQUEST:'EDIT_BOARD_REQUEST',
    EDIT_BOARD_SUCCESS:'EDIT_BOARD_SUCCESS',
    EDIT_BOARD_FAILURE:'EDIT_BOARD_FAILURE'
}